// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAiffgH_tkbPEHO8sEkI3rOod9TSl6fjME",
    authDomain: "profinfo-d1f2c.firebaseapp.com",
    projectId: "profinfo-d1f2c",
    storageBucket: "profinfo-d1f2c.firebasestorage.app",
    messagingSenderId: "1063777965196",
    appId: "1:1063777965196:web:0083f5bb4d5f048ac357a9"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6JIWbvT03Zy6hE27drbb9WEg-YaaYjKk',
    appId: '1:1063777965196:android:195f128e163aabe8c357a9',
    messagingSenderId: '1063777965196',
    projectId: 'profinfo-d1f2c',
    storageBucket: 'profinfo-d1f2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDScwCPWsjnR5i0n-NvcWpbKsjV44mkw6w',
    appId: '1:1063777965196:ios:29a1030f76d822bec357a9',
    messagingSenderId: '1063777965196',
    projectId: 'profinfo-d1f2c',
    storageBucket: 'profinfo-d1f2c.firebasestorage.app',
    iosBundleId: 'com.example.profinfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDScwCPWsjnR5i0n-NvcWpbKsjV44mkw6w',
    appId: '1:1063777965196:ios:29a1030f76d822bec357a9',
    messagingSenderId: '1063777965196',
    projectId: 'profinfo-d1f2c',
    storageBucket: 'profinfo-d1f2c.firebasestorage.app',
    iosBundleId: 'com.example.profinfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiffgH_tkbPEHO8sEkI3rOod9TSl6fjME',
    appId: '1:1063777965196:web:f9d5464c0a70122dc357a9',
    messagingSenderId: '1063777965196',
    projectId: 'profinfo-d1f2c',
    authDomain: 'profinfo-d1f2c.firebaseapp.com',
    storageBucket: 'profinfo-d1f2c.firebasestorage.app',
  );

}